esphome:
  name: gaszaehler
  platform: ESP8266
  board: d1_mini
  name_add_mac_suffix: False

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "gaszaehler Fallback Hotspot"
    password: "l8gsEEqCzHfT"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

number:
  - platform: template
    name: "Korrektur Zählerstand"
    unit_of_measurement: 'm³'
    min_value: 0.00
    max_value: 99999.99
    restore_value: true
    step: 0.01
    optimistic: true
    mode: 'box'
    id: gascorrection
    on_value:
      then:
        - pulse_meter.set_total_pulses:
            id: gaspulse
            value: !lambda |- 
              return id(gascorrection).state * 100;

sensor:
  - platform: pulse_meter
    pin: D6
    unit_of_measurement: 'dm³'
    internal_filter: 200ms
    accuracy_decimals: 2
    id: gaspulse
    filters:
      - multiply: 10 # (10/1000 per m³)

    total:
      device_class: 'gas'
      state_class: 'total_increasing'
      unit_of_measurement: 'm³'
      id: gastotal
      icon: mdi:counter
      name: "Gaszählerstand"
      accuracy_decimals: 3
      filters:
        - multiply: 0.01 # (m³)

binary_sensor:
  - platform: gpio
    pin:
      number: D6
      inverted: true
      mode:
        input: True
        pullup: True
    name: "Gasticksensor"
    filters:
      - delayed_off: 200ms
    on_press:
      then:
        - switch.toggle: statled
        - delay: 1s
        - switch.toggle: statled

switch:
  - platform: gpio
    pin: D4
    id: statled
    entity_category: "config"
    inverted: true

web_server:
  port: 80